### PR TITLE
[14.0][ADD] usability_base_exception

### PR DESCRIPTION
**Pull request by kittiu**
This module base off `base_exception` and add exception messages on following cases,

1. PR -> PO :: Purchase Order total amount shouldn't exceed that of PR amount.
2. PO -> Bill :: Vendor Bills(s) total amount shouldn't exceed that of PO amount.

When the exception occur, user can by pass it by set flag "Bypass Amount Exception",
then click confirm again.

### CODE REVIEW

**Comment by kittiu** [comment]
Sample, PR = 100, PO = 101. Confirm PO will get this error message.

To bypass error, check Bypass Amount Exception

image

@newtratip you can use this in HII.

**Comment by kittiu** [comment]
@newtratip there are still many Dynamic Report error on pre-commit. Can you check please?

**Comment by newtratip** [comment]
> @newtratip there are still many Dynamic Report error on pre-commit. Can you check please?

ok, I will check.

**Comment by newtratip** [comment]
@kittiu, Fixed.

**Pull request merged**
